name: "Terraform CI/CD"

on:
  push:
    branches:
      - main

jobs:
  terraform:
    name: "Terraform Apply"
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the code
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Azure CLI Manual Login
      - name: Azure CLI Login (Manual)
        run: |
          az login --service-principal \
            -u "${{ secrets.AZURE_USERNAME }}" \
            -p "${{ secrets.AZURE_PASSWORD }}" \
            --tenant "${{ secrets.AZURE_TENANT_ID }}"

      # Step 3: Setup Terraform
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: "1.4.0"

      # Step 4: Terraform Initialization
      - name: Terraform Init
        run: terraform init

      # Step 5: Terraform Plan
      - name: Terraform Plan
        run: terraform plan -input=false

      # Step 6: Terraform Apply
      - name: Terraform Apply
        run: terraform apply -auto-approve -input=false
